version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
      # После первого запуска задайте пароль для пользователя kibana_system вручную:
      # docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -i
      # Используйте этот пароль ниже вместо <KIBANA_SYSTEM_PASSWORD>
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-net
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:changeme", "-f", "http://localhost:9200/_cat/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  init-kibana-user:
    image: curlimages/curl:8.7.1
    container_name: init-kibana-user
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTIC_PASSWORD=changeme
    networks:
      - elastic-net
    volumes:
      - ./init-kibana-user.sh:/init-kibana-user.sh
    entrypoint: [ "sh", "/init-kibana-user.sh" ]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=true
    ports:
      - "5601:5601"
    depends_on:
      init-kibana-user:
        condition: service_completed_successfully
    networks:
      - elastic-net

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.11.1
    container_name: apm-server
    command: >
      apm-server -e
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.secret_token=""
        -E setup.kibana.host=kibana:5601
        -E setup.kibana.username=kibana_system
        -E setup.kibana.password=changeme
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E apm-server.kibana.username=kibana_system
        -E apm-server.kibana.password=changeme
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=changeme
    ports:
      - "8200:8200"
    depends_on:
      init-kibana-user:
        condition: service_completed_successfully
    networks:
      - elastic-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic-net:
    driver: bridge 